-- ============================================================
-- Glosario clínico — expansión temática: evaluación psicológica,
-- psicología forense/penitenciaria, psicología humanista e
-- inteligencias múltiples (Gardner).
-- Ejecutar en el editor SQL de Supabase (proyecto de Psicoteca).
--
-- user_id: se resuelve con un subquery a auth.users por tu correo, así el
-- script corre tal cual, sin que tengas que pegar tu UUID a mano. Si tu
-- cuenta de Supabase usa un correo distinto a luis.x.bm@icloud.com, cámbialo
-- en las 4 líneas "where email = ...".
--
-- 111 términos en total (50 evaluación psicológica, 26 forense/penitenciaria,
-- 22 humanista, 13 inteligencias múltiples). Contenido escrito desde
-- conocimiento clínico general de estos marcos teóricos (no extraído de
-- documentos concretos) — ver la aclaración dada en el chat.
-- ============================================================

-- --- 1) Modelos y técnicas de evaluación psicológica (50) ------------------
insert into public.glosario_clinico (user_id, termino, definicion, categoria) values
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo psicométrico (evaluación psicológica)',
   'Enfoque que concibe los atributos psicológicos (inteligencia, personalidad, aptitudes) como rasgos relativamente estables y cuantificables, medidos mediante instrumentos estandarizados con propiedades psicométricas (fiabilidad, validez, baremos normativos) que permiten ubicar al sujeto respecto a un grupo de referencia.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo dinámico (evaluación psicológica)',
   'Enfoque de raíz psicoanalítica que entiende la conducta como expresión de conflictos, motivaciones y mecanismos de defensa inconscientes; la evaluación busca inferir la estructura y dinámica de la personalidad más allá de la conducta manifiesta, típicamente mediante técnicas proyectivas.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo médico (evaluación psicológica)',
   'Enfoque categorial que asimila los trastornos psicológicos a entidades nosológicas discretas (síndromes o enfermedades) con etiología, curso y tratamiento propios; la evaluación se orienta al diagnóstico diferencial conforme a sistemas clasificatorios (CIE, DSM).',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo conductual (evaluación psicológica)',
   'Enfoque que concibe la conducta, incluida la considerada patológica, como aprendida y mantenida por sus relaciones funcionales con el ambiente; la evaluación (análisis funcional) identifica antecedentes y consecuentes de la conducta problema en lugar de rasgos subyacentes.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo cognitivo (evaluación psicológica)',
   'Enfoque centrado en los procesos de procesamiento de información (percepción, atención, memoria, esquemas, creencias) que median entre el estímulo y la respuesta; evalúa pensamientos automáticos, distorsiones cognitivas y esquemas disfuncionales.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo constructivista (evaluación psicológica)',
   'Enfoque que entiende al sujeto como constructor activo de significados sobre sí mismo y su mundo (constructos personales, narrativas); la evaluación es idiográfica y colaborativa, más interesada en el sentido subjetivo que en la comparación normativa.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo psicobiológico (evaluación psicológica)',
   'Enfoque que vincula las diferencias individuales de personalidad y conducta con sustratos biológicos (genética, neurotransmisores, activación del sistema nervioso central), evaluando marcadores psicofisiológicos junto a las medidas conductuales clásicas.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Modelo integrador o biopsicosocial (evaluación psicológica)',
   'Enfoque que combina variables biológicas, psicológicas y sociales para explicar y evaluar un caso concreto, evitando reducir la formulación clínica a un único nivel de análisis.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Técnicas objetivas (evaluación psicológica)',
   'Instrumentos de evaluación con formato estructurado y corrección estandarizada, habitualmente cuestionarios de ítems cerrados, que minimizan la subjetividad del examinador y permiten comparar la puntuación del sujeto con baremos normativos.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Técnicas subjetivas (evaluación psicológica)',
   'Instrumentos que recogen el autoinforme del sujeto sobre sí mismo (entrevistas, autoinformes abiertos, escalas de autopercepción) sin un criterio de corrección totalmente estandarizado, dependiendo en parte de la interpretación clínica.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Técnicas proyectivas (evaluación psicológica)',
   'Instrumentos que presentan estímulos ambiguos o poco estructurados (manchas, láminas, dibujos) bajo el supuesto de que la persona proyecta en su respuesta contenidos inconscientes, conflictos y rasgos de personalidad no accesibles a técnicas más estructuradas.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Entrevista clínica',
   'Técnica de recogida de información mediante interacción verbal directa entre evaluador y evaluado; puede ser estructurada, semiestructurada o libre, y constituye habitualmente el primer y más flexible instrumento de cualquier proceso de evaluación.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Observación conductual',
   'Técnica de evaluación que registra de forma sistemática la conducta del sujeto en su contexto natural o análogo, permitiendo cuantificar frecuencia, duración o intensidad sin depender del autoinforme.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Autorregistro',
   'Procedimiento de evaluación en el que el propio sujeto anota de manera sistemática la aparición de una conducta, pensamiento o emoción junto con su contexto, útil tanto para la evaluación como para el propio proceso terapéutico.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Escala de estimación (evaluación psicológica)',
   'Instrumento en el que el evaluador o el propio sujeto puntúa la presencia o intensidad de una característica en una escala ordinal (p. ej. tipo Likert), utilizado tanto en cuestionarios como en la codificación de entrevistas.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Fiabilidad (psicometría)',
   'Propiedad de un instrumento de medida que indica el grado de consistencia y estabilidad de sus puntuaciones, libre de error de medida aleatorio; se estima, entre otros métodos, mediante consistencia interna, test-retest o acuerdo entre observadores.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Validez (psicometría)',
   'Propiedad de un instrumento que indica el grado en que mide realmente el constructo que pretende medir y no otra cosa; incluye modalidades como la validez de contenido, de criterio y de constructo.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Baremo',
   'Tabla de referencia que transforma la puntuación directa de un sujeto en un instrumento en una puntuación relativa (percentil, puntuación típica) respecto a la distribución de un grupo normativo comparable.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Percentil (psicometría)',
   'Puntuación derivada que indica el porcentaje de sujetos de un grupo normativo que obtienen una puntuación igual o inferior a la del sujeto evaluado, facilitando la interpretación relativa de un resultado.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Puntuación típica o estándar (psicometría)',
   'Puntuación derivada que expresa la distancia entre la puntuación directa de un sujeto y la media del grupo normativo en unidades de desviación típica, permitiendo comparar resultados entre escalas distintas.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Sensibilidad y especificidad (evaluación psicológica)',
   'Propiedades de un instrumento de cribado o diagnóstico: la sensibilidad indica su capacidad de detectar correctamente a quienes presentan la condición evaluada, y la especificidad su capacidad de descartar correctamente a quienes no la presentan.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Validez ecológica (evaluación psicológica)',
   'Grado en que los resultados obtenidos con un instrumento o procedimiento de evaluación en un contexto controlado se corresponden con el funcionamiento real del sujeto en su vida cotidiana.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de Rorschach',
   'Técnica proyectiva compuesta por diez láminas de manchas de tinta simétricas; el examinado indica qué percibe en cada una, y las respuestas se codifican según localización, determinantes y contenido (p. ej. sistema de Exner) para inferir estilo perceptivo, control emocional y estructura de personalidad.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'TAT (Test de Apercepción Temática)',
   'Técnica proyectiva de Murray compuesta por láminas con escenas ambiguas sobre las que el sujeto elabora una historia (personajes, antecedentes, desenlace); el análisis del contenido narrativo revela necesidades, conflictos y patrones relacionales predominantes.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'CAT (Test de Apercepción Infantil)',
   'Adaptación del TAT para población infantil que sustituye las escenas con figuras humanas por escenas con animales, facilitando la proyección de contenidos por parte de niños pequeños.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de la figura humana (Machover)',
   'Técnica proyectiva gráfica en la que se solicita al examinado dibujar una figura humana; aspectos formales del dibujo (tamaño, trazo, ubicación, omisiones, énfasis en partes del cuerpo) se interpretan como indicadores de autoimagen, ansiedad y conflictos.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test del árbol (Koch)',
   'Técnica proyectiva gráfica en la que se solicita dibujar un árbol; sus características formales se interpretan, de modo análogo al test de la figura humana, como indicadores simbólicos del desarrollo y la dinámica de la personalidad.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de la familia (técnica proyectiva)',
   'Técnica proyectiva gráfica en la que se solicita dibujar una familia, real o imaginaria; la posición, tamaño y omisión de las figuras se interpreta como indicador de la dinámica vincular percibida por quien dibuja.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Persona bajo la lluvia (técnica proyectiva)',
   'Técnica proyectiva gráfica derivada del test de la figura humana en la que se solicita dibujar a una persona bajo la lluvia, interpretada como indicador de los recursos percibidos frente a situaciones de estrés o adversidad.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de Zulliger',
   'Técnica proyectiva de manchas de tinta derivada del Rorschach, compuesta por solo tres láminas, pensada para su aplicación colectiva o como instrumento de cribado más breve.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de Frases Incompletas de Sacks',
   'Técnica semiproyectiva en la que el sujeto completa el final de frases inconclusas referidas a distintas áreas vitales (familia, sexo, relaciones, autoconcepto), reveladoras de actitudes y conflictos.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'MMPI (Inventario Multifásico de Personalidad de Minnesota)',
   'Cuestionario objetivo de personalidad y psicopatología compuesto por cientos de ítems de verdadero/falso, organizado en escalas clínicas y de validez para detectar sesgos de respuesta (simulación, deseabilidad social); ampliamente usado en contextos clínicos, forenses y de selección.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'MCMI (Inventario Clínico Multiaxial de Millon)',
   'Cuestionario objetivo de personalidad basado en la teoría de Millon, orientado específicamente a la identificación de patrones de personalidad (incluidos los trastornos de personalidad) y síndromes clínicos asociados, coherente con una nosología multiaxial.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   '16PF (Cuestionario de Personalidad de Cattell)',
   'Cuestionario objetivo de personalidad que evalúa dieciséis factores de primer orden derivados mediante análisis factorial, agrupables a su vez en dimensiones globales de segundo orden.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'NEO-PI-R (Inventario de personalidad de los cinco grandes factores)',
   'Cuestionario objetivo que evalúa la personalidad conforme al modelo de los cinco grandes factores (neuroticismo, extraversión, apertura, amabilidad y responsabilidad), cada uno desglosado en facetas específicas.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'EPQ (Cuestionario de Personalidad de Eysenck)',
   'Cuestionario objetivo de personalidad basado en el modelo biológico de Eysenck, que evalúa las dimensiones de extraversión, neuroticismo y psicoticismo junto con una escala de sinceridad.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'PAI (Inventario de Evaluación de la Personalidad)',
   'Cuestionario objetivo de personalidad y psicopatología orientado a población clínica, con escalas de validez, clínicas, de tratamiento y de relación interpersonal.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Escalas Wechsler (WAIS/WISC)',
   'Familia de instrumentos psicométricos para la evaluación de la inteligencia en adultos (WAIS) y en niños/adolescentes (WISC), que arrojan un Cociente Intelectual global además de índices en dominios específicos (comprensión verbal, razonamiento perceptivo, memoria de trabajo, velocidad de procesamiento).',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de matrices progresivas de Raven',
   'Prueba no verbal de inteligencia fluida que exige completar la pieza que falta en una serie de matrices gráficas con complejidad creciente, minimizando la influencia del nivel cultural o educativo.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Escala de inteligencia de Stanford-Binet',
   'Uno de los primeros instrumentos psicométricos de inteligencia, derivado de la escala de Binet-Simon, que introdujo el concepto de edad mental y, posteriormente, el cociente intelectual.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test Gestáltico Visomotor de Bender',
   'Prueba que solicita copiar una serie de figuras geométricas, utilizada para detectar disfunción neuropsicológica, retraso madurativo o indicadores emocionales según la distorsión de la reproducción.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de Trazos (Trail Making Test)',
   'Prueba neuropsicológica que exige unir en orden una secuencia de números (parte A) o alternar números y letras (parte B), utilizada para evaluar atención sostenida, velocidad de procesamiento y flexibilidad cognitiva.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de clasificación de tarjetas de Wisconsin',
   'Prueba neuropsicológica que exige inferir una regla de clasificación cambiante a partir del feedback del examinador, utilizada para evaluar función ejecutiva y flexibilidad cognitiva asociada al funcionamiento prefrontal.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Test de Stroop',
   'Prueba neuropsicológica que mide la interferencia entre el nombre de un color y el color en que está impreso ese nombre, utilizada como medida de control inhibitorio y atención selectiva.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Figura Compleja de Rey-Osterrieth',
   'Prueba neuropsicológica que exige copiar y posteriormente reproducir de memoria una figura geométrica compleja, evaluando organización perceptiva, planificación y memoria visual.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'MMSE (Mini-Examen del Estado Mental)',
   'Instrumento breve de cribado cognitivo que explora orientación, memoria, atención, lenguaje y praxis, ampliamente utilizado en la detección inicial de deterioro cognitivo y demencia.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inventario de Depresión de Beck (BDI)',
   'Cuestionario autoaplicado que evalúa la intensidad de la sintomatología depresiva a partir de un conjunto de ítems referidos a síntomas cognitivos, afectivos, motivacionales y somáticos.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inventario de Ansiedad de Beck (BAI)',
   'Cuestionario autoaplicado que evalúa la intensidad de la sintomatología ansiosa, centrado especialmente en síntomas somáticos de la ansiedad, diferenciándola de la sintomatología depresiva.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'STAI (Cuestionario de Ansiedad Estado-Rasgo)',
   'Instrumento de Spielberger que distingue entre la ansiedad como estado transitorio ligado a una situación concreta y la ansiedad como rasgo relativamente estable de la personalidad.',
   'Evaluación psicológica'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Escala de Autoestima de Rosenberg',
   'Escala breve y unidimensional que evalúa el grado de valoración global que una persona tiene de sí misma, ampliamente utilizada por su brevedad y sus buenas propiedades psicométricas.',
   'Evaluación psicológica');

-- --- 2) Psicología penitenciaria y forense (26) -----------------------------
insert into public.glosario_clinico (user_id, termino, definicion, categoria) values
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Psicología penitenciaria',
   'Rama aplicada de la psicología que interviene en el contexto de instituciones de privación de libertad, abarcando la evaluación de personalidad y riesgo, el tratamiento y reinserción, y el asesoramiento a la institución sobre clasificación y régimen del interno.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Estudio inicial de personalidad (contexto penitenciario)',
   'Evaluación psicológica realizada al ingreso del interno en el centro penitenciario, orientada a describir su estructura de personalidad, historia biográfica y factores de riesgo, como base para el programa individualizado de tratamiento y la clasificación penitenciaria.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Conducta criminal (o delictiva)',
   'Comportamiento que infringe la norma penal vigente; desde la psicología se estudia como resultado de la interacción entre factores disposicionales (personalidad, aprendizaje) y situacionales (oportunidad, contexto social), sin reducirse a una única causa individual.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Culpabilidad (psicología jurídica)',
   'Categoría jurídico-psicológica que remite a la capacidad del sujeto de comprender la ilicitud de su acto y de actuar conforme a esa comprensión; su valoración pericial requiere diferenciar la imputabilidad clínica de la responsabilidad penal, que es una decisión estrictamente judicial.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Perversión (como posición subjetiva)',
   'En el marco psicoanalítico, estructura clínica definida no por la conducta observable sino por una posición subjetiva particular ante la ley y el deseo del Otro (p. ej., el desconocimiento de la castración), distinta del uso coloquial del término como sinónimo de conducta moralmente reprobable.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Peligrosidad criminal',
   'Constructo pericial que estima la probabilidad de que una persona reincida en conductas delictivas o violentas, habitualmente mediante instrumentos actuariales o de juicio clínico estructurado que ponderan factores de riesgo estáticos y dinámicos.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Imputabilidad',
   'Capacidad psicológica y jurídica de una persona para comprender la ilicitud de sus actos y de actuar conforme a esa comprensión en el momento de los hechos; su ausencia total (inimputabilidad) o parcial (semiimputabilidad) modula la responsabilidad penal.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inimputabilidad',
   'Ausencia de la capacidad de comprender la ilicitud del acto o de actuar conforme a esa comprensión, habitualmente por causa de anomalía o alteración psíquica grave, que exime o modula la responsabilidad penal conforme a la valoración pericial y judicial.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Trastorno mental transitorio (psicología jurídica)',
   'Alteración psíquica de aparición brusca, intensidad suficiente y duración limitada, sin base patológica permanente, que puede afectar a la imputabilidad del sujeto en el momento concreto de los hechos.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Simulación (contexto forense)',
   'Producción intencionada y exagerada de síntomas psicológicos o físicos, inexistentes o amplificados, motivada por un beneficio externo reconocible (evitar responsabilidad penal, obtener una indemnización); su detección es un objetivo específico de la pericia forense.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Disimulación (contexto forense)',
   'Ocultación o minimización intencionada de síntomas o características reales por parte del evaluado, con el fin de aparentar normalidad o mayor capacidad de la que efectivamente presenta.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Valoración del daño psíquico',
   'Pericia que determina la existencia, intensidad y relación de causalidad de una alteración psicológica derivada de un hecho concreto (accidente, agresión, negligencia), diferenciando el daño psíquico agudo de las secuelas permanentes.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Secuelas psíquicas (valoración del daño)',
   'Alteraciones psicológicas estabilizadas y permanentes que persisten tras el proceso agudo derivado de un hecho traumático, y que son objeto de valoración pericial a efectos de indemnización o incapacidad.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Victimología',
   'Disciplina que estudia a la víctima del delito, su relación con el victimario, el proceso de victimización y las consecuencias psicológicas de haber sido víctima, así como su papel en el proceso penal.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Credibilidad del testimonio',
   'Análisis pericial de la validez y fiabilidad del relato de un testigo o víctima, mediante criterios de contenido (p. ej. CBCA) que discriminan entre memorias de experiencias vividas y relatos fabricados o sugeridos.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Psicopatía (Hare / PCL-R)',
   'Constructo de personalidad caracterizado por un patrón estable de insensibilidad afectiva, manipulación interpersonal y estilo de vida antisocial e impulsivo, evaluado mediante instrumentos específicos como la Escala de Evaluación de Psicopatía de Hare (PCL-R), distinto del trastorno antisocial de la personalidad del DSM.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Trastorno antisocial de la personalidad',
   'Patrón persistente de desprecio y violación de los derechos de los demás, con inicio en la infancia o adolescencia (trastorno disocial) y continuidad en la vida adulta, caracterizado por impulsividad, engaño y ausencia de remordimiento.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Perfilación criminal (criminal profiling)',
   'Técnica de investigación que infiere características probables del autor de un delito (rasgos de personalidad, estilo de vida, posible perfil demográfico) a partir del análisis de la escena del crimen y el modus operandi.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Clasificación penitenciaria (grados)',
   'Sistema que asigna a cada interno un régimen de vida, de grados de tratamiento más restrictivos al régimen abierto, en función de su personalidad, historial delictivo, evolución del tratamiento y pronóstico de reinserción.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Programa individualizado de tratamiento (PIT)',
   'Plan de intervención penitenciaria diseñado a medida de cada interno a partir del estudio inicial de personalidad, que define los objetivos, actividades y recursos terapéuticos orientados a su reinserción social.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Informe pronóstico de reinserción social',
   'Documento pericial que valora, a partir de factores de riesgo y protección, la probabilidad de que un interno se reintegre socialmente sin reincidir, utilizado como apoyo a decisiones de progresión de grado o libertad condicional.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Factores de riesgo estáticos y dinámicos (valoración de peligrosidad)',
   'En la valoración de peligrosidad criminal, los factores estáticos son características históricas no modificables (edad de inicio delictivo, antecedentes), mientras que los dinámicos son variables actuales susceptibles de cambio mediante intervención (consumo de sustancias, impulsividad).',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Libertad condicional',
   'Situación penitenciaria en la que el interno cumple la parte final de su condena en libertad bajo determinadas condiciones, previo informe favorable sobre su pronóstico de reinserción y buena conducta.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Régimen abierto (penitenciario)',
   'Grado de clasificación penitenciaria con menor nivel de control y mayor autonomía del interno, orientado a la preparación gradual para la vida en libertad, habitualmente mediante salidas laborales o formativas.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Guarda y custodia (peritaje psicológico)',
   'Pericia psicológica en el contexto de procesos de familia, orientada a valorar las competencias parentales, el vínculo con cada progenitor y el interés superior del menor de cara a la decisión judicial sobre su custodia.',
   'Psicología forense'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Síndrome de alienación parental (concepto controvertido)',
   'Constructo, no reconocido como trastorno en los sistemas diagnósticos oficiales, que describe el rechazo de un menor hacia uno de sus progenitores atribuido a la influencia del otro; su uso pericial es objeto de fuerte debate científico y ético.',
   'Psicología forense');

-- --- 3) Psicología humanista y psicoterapia (22) ----------------------------
insert into public.glosario_clinico (user_id, termino, definicion, categoria) values
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Psicología humanista',
   'Corriente surgida a mediados del siglo XX como "tercera fuerza" junto al psicoanálisis y el conductismo, que sitúa en el centro la experiencia subjetiva, la libertad, el sentido y la tendencia natural del organismo hacia el crecimiento y la autorrealización.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Fenomenología (en psicoterapia)',
   'Método que prioriza la descripción de la experiencia vivida tal como se presenta a la conciencia del sujeto, suspendiendo los supuestos teóricos previos del terapeuta, para comprender el mundo subjetivo del cliente desde su propio marco de referencia.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Existencialismo (en psicoterapia)',
   'Marco filosófico que aborda las condiciones últimas de la existencia humana (libertad, responsabilidad, finitud, aislamiento, búsqueda de sentido) como ejes del malestar psicológico y del trabajo terapéutico, más que la psicopatología categorial.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Neurosis como alienación social (enfoque humanista)',
   'Lectura humanista que entiende el malestar neurótico no como una entidad clínica intrapsíquica aislada, sino como resultado de la desconexión del sujeto respecto de su experiencia genuina, producida por la internalización de condiciones de valía impuestas socialmente.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Terapia centrada en la persona (Rogers)',
   'Modelo psicoterapéutico humanista que confía en la tendencia actualizante del cliente y sostiene que el cambio terapéutico ocurre cuando el terapeuta ofrece consistentemente empatía, aceptación incondicional y congruencia, sin dirigir el contenido de la sesión.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Congruencia (Rogers)',
   'Condición terapéutica que describe la coherencia entre la experiencia interna del terapeuta, su conciencia de esa experiencia y su comunicación al cliente; junto con la empatía y la aceptación incondicional, constituye una de las tres condiciones necesarias y suficientes para el cambio terapéutico.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Tendencia actualizante (Rogers)',
   'Motivación innata que Rogers atribuye a todo organismo humano hacia el mantenimiento, el desarrollo y la ampliación de sus propias capacidades, considerada el motor natural del cambio terapéutico cuando las condiciones del entorno lo permiten.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Consideración positiva incondicional (Rogers)',
   'Actitud del terapeuta de aceptación cálida y no valorativa hacia la experiencia del cliente, independientemente de su contenido, que junto con la empatía y la congruencia constituye una de las tres condiciones terapéuticas necesarias del enfoque centrado en la persona.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Empatía (condición terapéutica rogeriana)',
   'Capacidad del terapeuta de comprender el marco de referencia interno del cliente con precisión y comunicárselo, sin perder la propia perspectiva; una de las tres condiciones necesarias y suficientes del cambio terapéutico según Rogers.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Autoconcepto (Rogers)',
   'Organización de percepciones y valoraciones que una persona tiene sobre sí misma; el malestar psicológico surge, en la teoría rogeriana, de la incongruencia entre el autoconcepto y la experiencia organísmica real.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Incongruencia (Rogers)',
   'Discrepancia entre la experiencia real del organismo y la representación que la persona tiene de sí misma (autoconcepto), fuente de ansiedad y de mecanismos defensivos que distorsionan o niegan la experiencia.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Locus de evaluación (Rogers)',
   'Lugar, interno o externo, desde el que una persona valora su propia experiencia y conducta; el desarrollo psicológico saludable se asocia a un desplazamiento progresivo hacia un locus de evaluación interno.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Terapia Gestalt (Perls)',
   'Modelo de psicoterapia humanista centrado en la conciencia del momento presente (aquí y ahora) y en la integración de las partes escindidas de la experiencia, con un fuerte componente experiencial y activo por parte del terapeuta.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Darse cuenta o awareness (terapia Gestalt)',
   'Concepto central de la terapia Gestalt que designa la conciencia plena y en contacto con la propia experiencia presente (sensaciones, emociones, pensamientos), considerada en sí misma un factor de cambio terapéutico.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Asuntos inconclusos (terapia Gestalt)',
   'Situaciones o vivencias emocionales del pasado que no fueron cerradas o integradas adecuadamente y que continúan interfiriendo en el presente, siendo objeto habitual de trabajo experiencial en la terapia Gestalt.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Técnica de la silla vacía (terapia Gestalt)',
   'Procedimiento experiencial de la terapia Gestalt en el que el cliente dialoga con una figura significativa ausente, o con una parte de sí mismo, representada en una silla vacía, para elaborar emociones no expresadas.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Ciclo de la experiencia (terapia Gestalt)',
   'Modelo que describe las fases sucesivas de un episodio de contacto organismo-ambiente (sensación, formación de figura, movilización de energía, acción, contacto, satisfacción y retirada), cuya interrupción en cualquier fase se asocia a distintos patrones de bloqueo.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Logoterapia (Frankl)',
   'Modelo de psicoterapia existencial que sitúa la búsqueda de sentido como la motivación humana fundamental, desarrollado por Viktor Frankl a partir de su experiencia en campos de concentración.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Voluntad de sentido (Frankl)',
   'Concepto central de la logoterapia que designa la motivación primaria del ser humano hacia encontrar un sentido a su propia existencia, en contraste con la voluntad de placer freudiana o la voluntad de poder adleriana.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Vacío existencial (Frankl)',
   'Sentimiento generalizado de falta de sentido y de vacío interior que, según Frankl, subyace a buena parte del malestar psicológico contemporáneo y que la logoterapia aborda directamente.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Psicología transpersonal',
   'Corriente, en ocasiones descrita como "cuarta fuerza" tras el humanismo, que incorpora al estudio psicológico las dimensiones espirituales, los estados de conciencia ampliados y las experiencias cumbre como aspectos legítimos del desarrollo humano.',
   'Psicología humanista'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Experiencias cumbre (Maslow)',
   'Momentos de intensa plenitud, unidad y trascendencia descritos por Maslow como manifestaciones puntuales del funcionamiento pleno del individuo, especialmente asociadas a personas orientadas hacia la autorrealización.',
   'Psicología humanista');

-- --- 4) Teoría de las inteligencias múltiples de Gardner (13) --------------
insert into public.glosario_clinico (user_id, termino, definicion, categoria) values
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Teoría de las inteligencias múltiples (Gardner)',
   'Modelo propuesto por Howard Gardner que cuestiona la noción de una inteligencia general (g) única y propone en su lugar un conjunto de capacidades relativamente autónomas, cada una con su propio sustrato neurológico y forma de procesar la información.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia lingüística',
   'Capacidad para usar el lenguaje de forma efectiva, tanto oral como escrita, incluyendo la sensibilidad al significado, sonido, ritmo y funciones de las palabras; propia de escritores, oradores y poetas.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia lógico-matemática',
   'Capacidad para razonar de forma deductiva e inductiva, reconocer patrones y relaciones abstractas, y manejar cadenas de razonamiento complejas; asociada tradicionalmente con las matemáticas, la lógica y el pensamiento científico.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia espacial',
   'Capacidad para percibir con precisión el mundo visoespacial y transformar esas percepciones, mentalmente o mediante representaciones gráficas; relevante en disciplinas como la arquitectura, las artes visuales y la navegación.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia musical',
   'Capacidad para percibir, discriminar, transformar y expresar formas musicales, incluyendo sensibilidad al ritmo, el tono, el timbre y la estructura de una pieza musical.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia corporal-cinestésica',
   'Capacidad para usar el propio cuerpo, o partes de él, con destreza para resolver problemas o crear productos, e incluye el control fino de los movimientos y la coordinación; propia de bailarines, deportistas y artesanos.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia interpersonal',
   'Capacidad para comprender las intenciones, motivaciones y deseos de otras personas, y para actuar eficazmente en la relación con ellas; base de habilidades como el liderazgo, la negociación y la empatía práctica.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia intrapersonal',
   'Capacidad para comprender los propios estados internos (deseos, emociones, motivaciones) y usar esa comprensión para regular la propia conducta y guiar decisiones vitales.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia naturalista',
   'Capacidad para reconocer, clasificar y utilizar elementos del entorno natural (especies de plantas y animales, fenómenos geológicos o climáticos); añadida posteriormente por Gardner a su modelo original de siete inteligencias.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia existencial (novena inteligencia propuesta)',
   'Capacidad propuesta posteriormente por Gardner para plantearse y reflexionar sobre cuestiones últimas de la existencia (el sentido de la vida, la muerte, el lugar del ser humano en el cosmos); no llegó a incorporarse plenamente como una inteligencia con el mismo estatus que las ocho originales.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Inteligencia emocional (Goleman)',
   'Constructo, distinto y posterior al de Gardner aunque frecuentemente asociado a él, que designa la capacidad de percibir, comprender y regular las propias emociones y las de los demás, popularizado por Daniel Goleman.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Estilos de aprendizaje (concepto relacionado)',
   'Preferencias individuales relativamente estables sobre el modo de percibir, procesar y organizar la información durante el aprendizaje; con frecuencia se relaciona, aunque no se identifica, con la teoría de las inteligencias múltiples.',
   'Inteligencias múltiples'),
  ((select id from auth.users where email = 'luis.x.bm@icloud.com'),
   'Crítica a la teoría de las inteligencias múltiples',
   'Objeción, principalmente desde la psicometría clásica, que cuestiona la falta de evidencia empírica robusta e independiente para cada inteligencia propuesta por Gardner y su escasa operacionalización mediante instrumentos estandarizados.',
   'Inteligencias múltiples');
